baseURL: "https://journalctl.dev"
title: ""
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableEmoji: true
googleAnalytics: G-JVXDZLK3KX

minify:
    disableXML: true
    minifyOutput: true

permalinks:
  posts: "/:year/:month/:day/:slug/"

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: /archive
                  url: /archives/
                  weight: 5
                - name: /search
                  url: /search/
                  weight: 10
                - name: /tags
                  url: /tags/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Scribbles of a Computer Programmer"
    author:
    - littichokha
    # author: ["Me", "You"] # multiple authors
    DateFormat: "2006-01-02"

    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    displayFullLangName: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: true
    ShowFullTextinRSS: true
    comments: true
    images:
    - /images/2021-12-24-man-at-the-library.jpg

    profileMode:
        enabled: false
        title: journalctl
        imageUrl: "#"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "journalctl"
        Content: >
          This is **journal** of a `developer.service` running in my _LifeOS_

    socialIcons:
        #- name: KoFi
          #url: "https://ko-fi.com/yudocaa"
        #- name: github
          #url: "https://github.com/sayanchowdhury"
        - name: email
          url: "mailto:namoskar@yudocaa.in"
        - name: twitter
          url: "https://www.twitter.com/yudocaa"
        - name: RSS
          url: "index.xml"

    cover:
         hidden: true # hide everywhere but not in structured data
         hiddenInList: true # hide on list pages and home
         hiddenInSingle: true # hide on single page

    fuseOpts:
         isCaseSensitive: false
         shouldSort: true
         location: 0
         distance: 1000
         threshold: 0.4
         minMatchCharLength: 0
         keys: ["title", "permalink", "summary", "content"]

    editPost:
        URL: "https://github.com/littichokha/journalctl.dev/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    label:
         text: "Home"
         icon: icon.png
         iconHeight: 35

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"



taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
